### ISSUE TITLE
Groups Button Should Go To Home Page

### ISSUE THREAD

**Issue by JimLynchCodes** [TDD-Solidity/EthDrop#1]
With gh-pages, the site is technically not hosted at the root '/' but rather at the 'EthDrop' route after the base domain...

The issue currently is that "Groups" button goes to the 404 page...

![Screen Shot 2021-07-31 at 10 58 41 AM](https://user-images.githubusercontent.com/5354163/127744723-c2d31576-5a63-4f99-8276-2baff7c55f73.png)

![Screen Shot 2021-07-31 at 10 58 49 AM](https://user-images.githubusercontent.com/5354163/127744748-d7cfce83-be1d-4b0f-85f1-f574e7c420d9.png)

notice that the url it jumps to is "tdd-solidity.github.io" and not the one it should be, "https://tdd-solidity.github.io/EthDrop/"

Fixing this bug should be as simple as having the button link to "/EthDrop/" rather than "/"

**Comment by latoyaallen** [comment]
PR to fix the issue: https://github.com/TDD-Solidity/EthDrop/pull/13
